baseURL = 'https://nocturne.no/'
locale = 'en'
title = 'Nocturnal Thoughts'
theme = 'nostyleplease'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = true
disableLanguages = []

[languages]
  [languages.no]
    title = "Nattlighet"
    label = "Norsk"
    weight = 1
  [languages.en]
    title = "Nocturnal Thoughts"
    label = "English"
    weight = 2

[markup.goldmark]

renderer.unsafe = true

[taxonomies]

series = 'series'